code/controllers/subsystems/ticker.dm, code/controllers/subsystems/vote.dm, code/controllers/subsystems/voting/poll_types.dm
Ports over the experimental voting that was well reserved
=> The voting changes

code/modules/research/xenoarchaeology/machinery/psionic_harvester.dm
Fixes the psionic harvester to not destroy the artifact inside if you click it a second time.
=> psionic harvester use fix

code/game/objects/structures/watercloset.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/human_frost.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/organs/external/subtypes/standard.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/food-Drinks.dm, liberty-station.dme
Adds in frost affects from being told code rather then just flat out strait burns
Not all that balanced other then around -20~cats you start to build some frost without interals
=> frost handling

code/game/gamemodes/events/weather.dm, code/game/gamemodes/events/weather/snow_storm.dm, liberty-station.dme, modular_liberty/area_blurbs.dm
Adds in the framework and some working code for snowing via the events
=> allows snowing

code/datums/helper_datums/construction_datum.dm, code/game/mecha/mecha.dm, code/game/mecha/mecha_construction/ivan.dm, code/modules/genetics/machinery/genetics_analyzer.dm, code/modules/research/experiment.dm
Ivan making now uses proper icons
RnD collection from genetics, and explosives now needs to be done by hand rather then sent, this should help prevent bugs with sci point dopping,
=> ivan tweak and rnd point collection

code/modules/power/hydroelectric.dm, maps/__Liberty/map/Underground_Old.dmm, maps/__Liberty/map/_Liberty_Colony_New.dmm, maps/__Liberty/map/_Liberty_Colony_Omni_STU.dmm, maps/__Liberty/map/_Liberty_Colony_Underground.dmm
Renames hydro damn to thermeral
Instead of removing trash you now remove scrap metal when it has stuck debris
=> renames hydro to themeral

code/_onclick/cyborg.dm, code/game/machinery/ai_slipper.dm, code/game/machinery/alarm.dm, code/game/machinery/doors/airlock.dm, code/game/objects/items/weapons/cards_ids.dm, code/game/objects/objs.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/syndicate.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/power/apc.dm
<details>
<summary>
No more "Head is made of head" For synthetics.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Reminded colonists that robots are, infact, robots. And they tend to be metal by nature.
/:cl:
=> Colonists remember robots are made of robot

code/_onclick/cyborg.dm, code/game/machinery/ai_slipper.dm, code/game/machinery/alarm.dm, code/game/machinery/doors/airlock.dm, code/game/objects/items/weapons/cards_ids.dm, code/game/objects/objs.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/syndicate.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/power/apc.dm
<details>
<summary>
What it do. Remove borg all-access, gives access based on department(currently equal to fellow employees)
</summary>
<hr>
<hr>
</details>
:cl:
tweak: changed some shit
balance: probably fuckered up the balance somewhere.
/:cl:
=> Borgeration

code/datums/setup_option/backgrounds/ancestry/ancestry_synthetic.dm
Descriptions courtesy of grimbo :)
<details>
<summary>
</summary>
<hr>
<hr>
</details>
=> Update Descriptions for Union synthetics

code/modules/surgery/mods.dm, code/modules/surgery/organic.dm, code/modules/surgery/organic_damage.dm, code/modules/surgery/robotic.dm, code/modules/surgery/robotic_damage.dm, code/modules/surgery/wound_repair.dm
<details>
<summary>
Fixes surgery fail_steps to work with new internal organ damage
</summary>
<hr>
<hr>
</details>
:cl:
tweak: probably nerfs things
/:cl:
=> Fail steps inlined with new internal organ damage

code/datums/craft/recipes/guild.dm, code/game/objects/items/weapons/autolathe_disk/guild_disks.dm, code/game/objects/items/weapons/tools/mods/mod_types.dm, code/game/objects/random/tool_mods.dm, code/modules/projectiles/guns/projectile/revolver/old/breakaction.dm, code/modules/research/designs/weapon.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/advtechno.dm
<details>
<summary>
</summary>
<hr>
Does as discussed with Terra-Therma contributors.
- Removes T4 nanoforge parts; as this would be very strong self-supplying due to having mining now. (T5s have been kept due to needing Sci to supply.)
- Removes chainsaw from Forge (useless for complex guild crafting, inferior to hypersaw).
- Removes crafting recipes for stuff already on the disk and/or forge.
- Removes gun crafting FOR NOW while I wait for Therma to decide what the fuck they're doing gun wise.
<hr>
</details>
:cl:
removes: Mundane Guild crafting recipes; we have a forge and disks for this. No one ever makes these by hand due to inefficency.
removes: T4 round-start parts. Kept T5s to encourage trading.
removes: Guns from Guild crafting; **THIS IS TEMPORARY** while …
=> Terra Therma Changes

maps/_DeepForest/map/frozen_forest.dmm, maps/__Liberty/area/_Liberty_areas.dm
Simil now is properly protected from weather
Renames some area names to be more discriptive
=> frozen forest fixes

code/__DEFINES/jobs.dm, code/game/jobs/job/service.dm, code/game/jobs/jobs.dm, code/modules/multiz/map_data.dm
<details>
<summary>
</summary>
<hr>
Title
<hr>
</details>
:cl:
tweak: Bouncer to Fixer
/:cl:
=> Bouncer to Fixer

code/_onclick/hud/screen_objects/base_screen_objects.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species/species.dm
<details>
<summary>
currently it compiles, it triggers properly the ifs, but does "work"
</summary>
<hr>
- turns out erismed was to blame
- it SHOULD work now, will still require heavy live testing to account for unforeseen methods to hurt yourself (hopefully eating spicy food won't trigger it this time)
<hr>
</details>
:cl:
add: you now take lung damage if you breath in a way too cold/hot environment
add: take freeze burns if you decide to go naked in the cold
add: nearly all hud elements have a description now
/:cl:
=> temperature revolution and it's consequences

code/modules/research/designs/circuits.dm, code/modules/research/nodes/biotech.dm, code/modules/research/nodes/similacrum.dm
<details>
<summary>
</summary>
<hr>
Removes majority of greyson (simalacrum) research options from RnD as all they do is cause problems on top of a lot of them already having an alternative to them in existing trees.
Also shoves medfab board under biotech tree
<hr>
</details>
:cl:
add: Medfab board to RnD tree
del: Most of greyson event "rewards"
/:cl:
=> Event rewards be like

code/modules/reagents/reagent_containers/glass/beaker.dm
this should stop linters being angy all the time, or at lest help
=> fixes a runetime with beakers

code/game/objects/random/mob/roach.dm, code/modules/mob/living/carbon/superior_animal/roach/roach.dm, code/modules/mob/living/carbon/superior_animal/roach/types/benzin.dm, code/modules/mob/living/carbon/superior_animal/roach/types/bluespace.dm, code/modules/mob/living/carbon/superior_animal/roach/types/emp.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fatty.dm, code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm, code/modules/mob/living/carbon/superior_animal/roach/types/glowing.dm, code/modules/mob/living/carbon/superior_animal/roach/types/hunter.dm, code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm, code/modules/mob/living/carbon/superior_animal/roach/types/nanites.dm, code/modules/mob/living/carbon/superior_animal/roach/types/plasmaroach.dm, code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm, code/modules/mob/living/carbon/superior_animal/roach/types/support.dm, code/modules/mob/living/carbon/superior_animal/roach/types/tank.dm, code/modules/mob/living/carbon/superior_animal/roach/types/tazntz.dm, code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm, code/modules/reagents/reagent_containers/food/snacks/burger.dm, code/modules/reagents/reagent_containers/food/snacks/meat.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/McRonalds.dm
<details>
<summary>
</summary>
<hr>
Renames roaches to non german names
Kampfer > Overgrown Roach
Benzin > Fireball Roach
Unbekannt > Bluespace Roach
Elektromagnetisch > Ion Roach
Obese Kampfer > Overfed Roach
Fuhrer > Overlord Roach 
Kaiser > Hivelord Roach
Gluhend > Glowing Roach
Jager > Hunter-Killer Roach
Kraftwerk > Nanite Roach
Brennbar > Phoron Roach
Roachling > Roach
Seuche > Vapour Roach
Panzer > Exoskeleton Roach
Tazntz > Eldritch Roach
Gestrahlte > Radioactive Roach
Buffs roach damage output over the board as they were considered "weak" a lot of the time by certain people
<hr>
</details>
:cl:
add: New roach names
balance: Roach menance
/:cl:
=> The maint monsters are bountiful

code/modules/core_implant/cruciform/machinery/armaments.dm, code/modules/projectiles/guns/energy/laser/sniperrifle.dm, code/modules/projectiles/guns/oddity_items.dm
<details>
<summary>
</summary>
<hr>
Small name fixes I neglected before.
<hr>
</details>
:cl:
fixes: Mismatched gun names.
/:cl:
=> Gun Name Corrections

code/game/objects/items/devices/defib.dm, code/modules/surgery/wound_repair.dm
halfs both timers for defibs
removes fixing time-of-death via surgery
=> changes defibs to be less strong

maps/__Liberty/map/_Liberty_Colony.dmm
Fixes several missing map floors that caused atmos to dissapear, also fixes some space tiles and erroneous areas.
=> Colony map fixes

code/datums/craft/recipes/guild.dm
Omnitool recipe relied on currently unobtainable ingredients (printed upgrade parts).  Has been updated to use handmade parts.
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Fix Union Omnitool recipe

code/modules/projectiles/gun.dm, code/modules/projectiles/projectile.dm
<details>
<summary>
</summary>
<hr>
https://github.com/discordia-space/CEV-Eris/pull/8095
Hopefully removes the lag from full automatics, admins still have logs of these
<hr>
</details>
:cl:
del: Hit and fire messages
/:cl:
=> Hit messages

code/datums/craft/recipes/guild.dm, code/game/objects/items/weapons/tools/mods/_defines.dm, code/game/objects/items/weapons/tools/mods/_upgrades.dm, code/game/objects/items/weapons/tools/mods/armor_mods.dm
<details>
<summary>
adds slowdown, stiffness and obscuration as possible mods for armor (plating nerf, basically)
</summary>
<hr>
<hr>
</details>
:cl:
add: TT got back their platings
balance: but they now give slowdown and stiffness (0.2 and 0.1 respectivelly)
/:cl:
=> more armor mod stats (all "bad")

code/game/objects/items/weapons/storage/backpack.dm, code/modules/power/solar.dm
<details>
<summary>
my bad, deleted too hard 😔 
</summary>
<hr>
<hr>
</details>
:cl:
fix: fixes anyone acessing their backpacks/dufflebags when only slime are allowed to do so
/:cl:
=> backpack fix

maps/__Liberty/map/_Liberty_Colony.dmm
=> greatly explains and improves maints

code/modules/mob/living/carbon/human/human.dm
<details>
<summary>
what it says on the title
</summary>
<hr>
<hr>
</details>
:cl:
fix: slime people are now slightly transparent
/:cl:
=> slimes are slightly transparent

maps/__Liberty/map/_Liberty_Colony.dmm
Last little section of maints has been fully finished
=> makes the last part of maints looks like maints

maps/__Liberty/map/_Liberty_Colony.dmm
<details>
<summary>
found some issues, took care of them
</summary>
<hr>
<hr>
</details>
:cl:
fix: entrance of the colony's administrative room now has floor
fix: burning chamber in atmos now has a proper injector that can be operated by the computer
tweak: gatehouse air supply now has a passive gate, for a future thing I will add later properly
balance: all entrances to the colony now have vents + scrubbers on to save some stress from engineering early into the shift with air alerts
/:cl:
=> minor map fixes + atmos prep

maps/__Liberty/map/_Liberty_Colony.dmm
<details>
<summary>
</summary>
<hr>
Adjusts the bar a bit. Plus fixes some lighting issues.
<hr>
</details>
:cl:
/:cl:
=> Map Update

code/modules/mob/living/carbon/human/species/station/station.dm
<details>
<summary>
</summary>
<hr>
Maybe fixes slime issues of digestion and being unable to eat food. This is due to lacking a stomach, thus unable to get nutriants. 
No idea how to fix its issue with being unable to eat or whatever since I couldn't even get a solid answer on the bug generally when asking of: "Can it not eat or can it just not digest the food?" - so. Here. 
This is why I despise this fetish-snowflake species.
<hr>
</details>
:cl:
fixes: Maybe fixes slimes being unable to eat. Suffer.
/:cl:
=> Maybe fixes slime digestion

code/game/turfs/flooring/flooring_premade.dm, maps/__Liberty/map/_Liberty_Colony.dmm
Replaces many maints tiles with the new ones from F13, making maints more rundown
Fixes some wires, pipes and map issues
Made sure theirs plenty of wall fire lockers, o2 lockers, and other misc things of that sort
=> more map fixes and wall stuff

code/modules/mining/mine_items.dm, maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm, maps/__Liberty/map/_Liberty_Colony.dmm
<details>
<summary>
now miners can work, REJOICE!
</summary>
<hr>
<hr>
</details>
:cl:
fix: various access issues for miners, both in code and in map
fix: a hole into space
fix: some names in doors
:cl:
=> Fixes mining

code/datums/setup_option/core_implants.dm, code/game/machinery/cryo.dm, code/game/objects/items/devices/defib.dm, code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/modules/mob/living/silicon/robot/gripper.dm, code/modules/organs/internal/psionic.dm, code/modules/psionics/psion_powers/teleporation_powers.dm
Disables some things not yet ready without a rework
Makes cryo pods statis death timer
ups defib time to 20 mins from 15
adds tons of statis bags to medical and scav roles lockers
=> disables some bad things and adds more stats bags

code/modules/power/port_gen.dm
:cl:
fix: runtime in port_gen
/:cl:
=> fixes runtime in port_gen.dm

code/modules/client/preference_setup/loadout/lists/utility.dm
:cl:
fixes: briefcases now show on loadout
/:cl:
=> fixes briefcases on loadout

maps/_dungeons/precursor/precursor.dm
disabled the precursor dungeon till its fully finished.
=> precursor temp disable

code/game/jobs/job/service.dm
Lets Club manager use their own office
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Gives acess_merchant to Club Manager

code/game/machinery/smelter.dm
<details>
<summary>
</summary>
<hr>
Title, ports https://github.com/discordia-space/CEV-Eris/pull/8093
<hr>
</details>
:cl: [MLGTASTICa](https://github.com/MLGTASTICa)
fix: Fixed infinite material duping exploit using smelters to get fractional sheets.
/:cl:
=> Ports #8093

code/datums/outfits/jobs/engineering.dm, code/game/jobs/job/engineering.dm
Removes Mining Technician's round-start Breaker and crowbar.
Adjusts Mining Technician's access to no longer include Engineering areas.
=> miner adjustments

code/__DEFINES/perks.dm, code/datums/perks/backgrounds.dm, code/datums/setup_option/backgrounds/habit/habit.dm
<details>
<summary>
</summary>
<hr>
Adds paper worm and removes the perks I didn't remove entirely cause I am stupid
<hr>
</details>
:cl:
add: Paper Worm
del: Carn/Herbivore finally entirely
/:cl:
=> Paper Worm

code/modules/reagents/reagent_containers/food/snacks/burger.dm
<details>
<summary>
no more fuhrole error message for the server yay!
</summary>
<hr>
<hr>
</details>
:cl:
del: deletes a chem that no longer exists
/:cl:
=> fix a burger

code/modules/mob/living/carbon/human/human.dm
<details>
<summary>
so, if you choose slime, then go back to human, you still keep the transparency, this tweak should fix it
</summary>
<hr>
<hr>
</details>
:cl:
fix: char creation from slime to anything does not keep you transparent as a slime anymore
/:cl:
=> forgot an else

code/modules/projectiles/guns/projectile/matter_guns/matter_pistol.dm
<details>
<summary>
balance might still be iffy, but it works as it should and I've made a define at the start of the file for easier balance
</summary>
<hr>
<hr>
</details>
:cl:
fix: Terra pistol using too much ammo all the time
balance: Terra guns ammo cost when compared to the RXD
/:cl:
=> Terra guns

code/__HELPERS/time.dm, code/global.dm, code/modules/games/spaceball_cards.dm
Adjusts the in-game year to 2723 like the lorehead says.
=> changes in-game year

code/game/jobs/job/engineering.dm
<details>
<summary>
more to come as lore team hands me the texts
</summary>
<hr>
<hr>
</details>
:cl:
fix: lore friendly Union Boss job description
/:cl:
=> Union boss job description

code/datums/lobbyscreen.dm
<details>
<summary>
</summary>
<hr>
Title
<hr>
</details>
:cl:
fix: Bad song
/:cl:
=> Changes le funny song to less le funny song ):

code/modules/vehicles/cargo_train.dm, code/modules/vehicles/train.dm
<details>
<summary>
turns out creating a tab on proximity is laggy clientside, no idea serverside
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Cargo tug no longer creates a tab, moves the things in the vehicle tab to the object tab
/:cl:
=> Cargo tug no longer lags the player when approaching

maps/__Liberty/map/_Liberty_Colony.dmm
Fixes missing disposal lines in Xenobiology and Genetics for both of their pens.
=> disposals fixes

maps/__Liberty/map/_Liberty_Colony.dmm
Fixes the stairs in the chapel being unwalkable.
=> chapel stair fix

code/game/objects/structures/flora/snowrocks.dm
Adjusts boulder descriptions and sets them to be dense as their sprite implies.
=> boulder tweaks

code/modules/mob/living/carbon/human/human.dm
Implants of the bondfire now spawn correctly
=> fixes implants not spawning

maps/__Liberty/data/reports.dm
<details>
<summary>
</summary>
<hr>
Makes report program templates bit more organized and usable with some of the inconsistencies fixed (like Watchmen being still called Officers)
<hr>
</details>
:cl:
fix: Report Program Templates
/:cl:
=> Report Templates

maps/__Liberty/map/_Liberty_Colony.dmm
Adds buttons to open the Mech Bay doors, giving Robots a way out of and into Robotics.
=> Adds button to open Mech Bay

code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/ghost_kitchen.dm
<details>
<summary>
</summary>
<hr>
Fixes wrong names on offers in beacon for roach burgers
<hr>
</details>
:cl:
fix: Old burger names
/:cl:
=> Offer burger names

code/modules/genetics/creatures/golden_roach.dm, maps/__Liberty/map/_Liberty_Colony.dmm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
add: adept blattedin is back
add: petrel pump is back, so is the fuel room
tweak: most of terra now has it's own grid, not on main grid anymore, but still partially on engine grid (mostly the bottom floor)
tweak: several substations/SMES/APC changed to make it easier to read troubles for Terra on the computers
add: firedoors in several places
add: Skylight garden got the animals back!
tweak: trays got moved around for the sake of the farmbot (none added/deleted)
tweak: atmos now starts 99% set up, no need to tweak every round
tweak: gatehouse atmos is a bit less of a problem, full "fix" coming at a later PR (it's the air alarms sensitivity)
fix: telecomms weird wiring
add: robotics now has 2 mechanical toolboxes and 2 electrical …
=> too many map changes

code/game/jobs/job/captain.dm
<details>
<summary>
</summary>
<hr>
Title
<hr>
</details>
:cl:
tweak: Board Secretary Description
/:cl:
=> Update Board Secretary Description

code/_onclick/cyborg.dm, code/game/machinery/ai_slipper.dm, code/game/machinery/alarm.dm, code/game/machinery/doors/airlock.dm, code/game/objects/items/weapons/cards_ids.dm, code/game/objects/objs.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/syndicate.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/power/apc.dm
This reverts commit 057b398dc5ed53997adb64defb6f8c046ff0b8b0.
Removes borgs access restictions again
=> Revert "Borgeration"

code/game/jobs/job/service.dm
gives fixers cargo access so they can open their lockers and the cargo windoor.
=> fixer access

code/modules/client/preference_setup/loadout/lists/armament.dm
Fixes the Clarissa and Pocket Prince guns in the loadout being unselectable.
=> fixes loadout guns

code/modules/research/nodes/combat.dm, code/modules/research/nodes/illegal.dm
<details>
<summary>
</summary>
<hr>
Reduces the power storage requirement by 2 since there are only 10 levels from 11 active nodes now and robotics for borg overclock
<hr>
</details>
:cl:
fix: Too high requirement on designs
/:cl:
=> Fixes R&D oversight

code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm, code/modules/trade/datums/trade_stations_presets/1-common/caduceus.dm, code/modules/trade/datums/trade_stations_presets/1-common/hellcat.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/suit_up.dm, code/modules/trade/datums/trade_stations_presets/3-rare/mecha.dm
<details>
<summary>
</summary>
<hr>
Makes trade beacon shuttles be closer to lore
<hr>
</details>
:cl:
tweak: Trade beacon shuttle names
/:cl:
=> Shuttle names

code/game/objects/items/oddities.dm, code/game/objects/items/weapons/cigs_lighters.dm, code/game/objects/random/oddities.dm, code/modules/client/preference_setup/loadout/lists/suits.dm, code/modules/clothing/accessories/accessory.dm, code/modules/clothing/suits/miscellaneous.dm, code/modules/clothing/suits/storage.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/solgov/marines.dm, code/modules/modular_computers/file_system/programs/generic/coin_miner.dm, code/modules/projectiles/guns/projectile/automatic/old/battlerifle.dm, code/modules/projectiles/guns/projectile/automatic/old/chaingun.dm, code/modules/projectiles/guns/projectile/pistol/old/ladon.dm, code/modules/projectiles/guns/projectile/pistol/old/lamia.dm, code/modules/reagents/reagent_containers/food/cans.dm, code/modules/reagents/reagent_containers/glass/beaker.dm, code/modules/trade/datums/trade_stations_presets/1-common/asterstradecapital.dm
<details>
<summary>
</summary>
<hr>
Replaces Solfed references with Terran
<hr>
</details>
:cl:
fix: Solfed Existing
/:cl:
=> Removes Solfed References

code/modules/power/generator.dm, tgui/packages/tgui/interfaces/TEGenerator.js
<details>
<summary>
i literally had to run this on tg codebade first for it to work, then tried here and now it works, JS for the UI taken from citadel 
</summary>
<hr>
choose one of those:
1. run bin/tgui-build.bat on the codebase for the ui to work (ignore the huge amount of warnings, since we are using eris deprecated TGUI), otherwise it won't
2. ask for my TGUI folder, it's too many files to make it a simple pr easy like that
<hr>
</details>
:cl:
code: TEG generator now uses TGUI
/:cl:
=> long story, short pr

code/game/jobs/department.dm, code/game/jobs/job/church.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/job.dm, code/game/jobs/job/service.dm
<details>
<summary>
</summary>
<hr>
Gives departments their money back instead of singular centralized account, always was only meant to be a temporary measure.
Fixes there being 2 service accounts making the skylight one unusable as it contained no jobs.
Reduces custodian wages except for forgemaster who gets a higher one and janitor wage as he is no longer part of neotheology (none of them are)
<hr>
</details>
:cl:
add: Departmental money back
balance: Wages on few jobs
fix: Skylight account
/:cl:
=> Department Dosh and Wages

code/modules/client/preference_setup/loadout/lists/factionphokorus.dm
Fixes PIRS loadout restrictions being set wrong
=> PIRS loadout clothes

code/datums/craft/recipes/guild.dm
:cl:
fix: some names/paths in crafting for Terra-Therma
/:cl:
=> renames some crafting stuff, more to come

nano/templates/chemistry_catalog.tmpl
medical catboy forgot this one
:cl:
fix: CIRC is no longer soteria in the nanoUI
/:cl:
=> CAPSA reagents

code/game/jobs/job/service.dm
increases fixer slots due to request. Might be lowered later if it gets strange.
=> fixer slot counts increase

code/modules/projectiles/guns/mods/mods.dm, code/modules/research/designs/weapon.dm, code/modules/research/nodes/combat.dm
<details>
<summary>
</summary>
<hr>
Changes 'Tesla' to be like on eris level (hurricane kit but for energy kits basically), reenables psionic catalyst and removes DNA lock from R&D tree as it's on their disk anyway
<hr>
</details>
:cl:
add: Psionic Catalyst
del: DNA lock from tree
balance: Buffs 'Tesla'
/:cl:
=> Psi and Tesla

code/game/jobs/job/service.dm, maps/__Liberty/map/_Liberty_Colony.dmm
Reverts Liberty-Landing/Liberty-Station-13#240
Fixes most job slots not having spawn points
=> Revert "fixer slot counts increase"

maps/__Liberty/map/_Liberty_Colony.dmm
Patches up a missing floor in the brig.
=> Fixes a missing floor in the brig

maps/__Liberty/map/_Liberty_Colony.dmm
no more garbage tossed on union grounds 🤬
:cl:
fix: missing pipe in disposal
/:cl:
=> fix disposal

code/modules/client/preference_setup/general/07_stats.dm
<details>
<summary>
</summary>
<hr>
Reduces total amount of points to 10 from 15, makes cog provide full points
<hr>
</details>
:cl:
balance: Skill screen
/:cl:
=> Skill screen

maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
:cl:
fix: wiring in the mines level got looked after, should be good now
/:cl:
=> wiring check in the mines

code/game/jobs/job/service.dm
<details>
<summary>
</summary>
<hr>
Gives fixers access to department account and removes raise the bar from them, they were never meant to actually work it instead of club workers
<hr>
</details>
:cl:
add: Fixer account access
del: Fixer raise the bar
/:cl:
=> Fixer momemntos

code/game/jobs/job/service.dm
<details>
<summary>
</summary>
<hr>
fixes the decision to make fixers bouncers and instead makes them what was agreed to and planned to be.
im sure next time i look we'll have gone back to the original proposal someone had of making them prostitutes.
<hr>
</details>
:cl:
fixes: Fixer description.
/:cl:
=> Fixes Fixer Description

code/game/machinery/vendor/misc_vendors.dm, code/game/objects/items/weapons/storage/fancy.dm, code/game/objects/items/weapons/storage/lunchbox.dm, code/game/objects/random/cigarettes.dm, code/modules/reagents/reagent_containers/food/cans.dm, code/modules/reagents/reagent_containers/food/drinks.dm, code/modules/reagents/reagent_containers/food/snacks/advanced_food.dm, code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
<details>
<summary>
</summary>
<hr>
Redone PR, without map changes this time and cohors stays too.
<hr>
</details>
:cl:
tweak: Vendor food/drink names
/:cl:
=> Vendor Food 2.0

code/controllers/subsystems/vote.dm
read title
:cl:
fix: vote not starting...hopefully
/:cl:
=> hopefully it's this causing the voting issues

code/__DEFINES/economy.dm, code/game/jobs/job/assistant.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/church.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/offcolony.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/jobs/job/service.dm
<details>
<summary>
</summary>
<hr>
Makes starting accounts bit less RNG based (still RNG based but it's just how it is)
<hr>
</details>
:cl:
balance: Starting account balance
/:cl:
=> Account Balance

code/game/objects/random/mob/golems.dm, code/game/objects/random/mob/misc.dm, code/game/objects/random/mob/roach.dm, code/game/objects/random/mob/slime.dm, code/game/objects/random/mob/spider.dm, code/game/objects/random/mob/termite.dm, maps/_DeepForest/map/frozen_crashsite.dmm
also adds documentation for mappers to know the numbers they are using Nerfs termite spawns in the crashsight map
=> reduces termite cluster/swarm and hoard spawns

code/modules/economy/economy_misc.dm, code/modules/modular_computers/file_system/news_article.dm, news_articles/Lionel_interview.html
<details>
<summary>
</summary>
<hr>
Actually adds the news channels that contain something and Bobinsky
<hr>
</details>
:cl:
add: Bobinsky
fix: News channels not existing
/:cl:
=> Actually makes news work

code/modules/client/preference_setup/loadout/lists/accessories.dm, code/modules/client/preference_setup/loadout/lists/utility.dm
<details>
<summary>
</summary>
<hr>
Moves wallet from accessories to utility to prevent it from constantly spamming attaching to clothes
<hr>
</details>
:cl:
fix: Wallet runtime
/:cl:
=> Fixes wallet runtime

maps/__Liberty/map/_Liberty_Colony.dmm
Never done a pr before, forgive me if i fucked it up somehow
-  Probably broke six other things but i tested it and it seemed to work fine.
-  Unfucks the broken wire in Terra therma.
- Removes the light switch in medical so seb can see. 
- Fixes the morgue boxes that are facing the wrong way in capsa 
- Adds a poker table and some more plants to skylight
=> Minor map bug fixes and additions. 

maps/_DeepForest/map/frozen_crashsite.dmm, maps/__Liberty/area/_Liberty_areas.dm
Toggles on dynamic lighting for indoor areas in Frozen Crashsite, adds outdoor lights where sensible.
=> Frozen Crash Site area dynamic lighting and outdoor lights

code/game/jobs/job/medical.dm, code/modules/projectiles/guns/projectile/boltgun/game.dm
Big hunter bolt gun when sawn now gives a sawn verson of the big hunter bolt gun, rather then base mosin
Paramedic now has maints access to save dieing people from maints
=> paramedic and gamer boltgun sawn thing

code/game/objects/items/weapons/autolathe_disk/guns_ammo_sec_disks.dm
Fixes a doup disk for the 10mm tactical making it have 9mm smg mags by misstake
=> Fixes tactical having smg 9mm

code/game/jobs/job/church.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm
Updates many job descriptions and duties to be more in-line with the server.
Draft until I can get a response from all the departments involved in this PR:
=> Updates various job descriptions and duties

code/game/jobs/job/engineering.dm, code/game/jobs/job/job.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/prospector.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
<details>
<summary>
</summary>
<hr>
Sadly these break manifest so going to be commented out for now
<hr>
</details>
:cl:
del: Comments out noob names
/:cl:
=> Disables noob names for now

code/modules/clothing/suits/armor.dm
<details>
<summary>
</summary>
<hr>
Adds a way for people to get rid of the pesky adjust style inheritence, also nerfs makeshift armor
<hr>
</details>
:cl:
add: Adjust style killer
balance: makeshift armor
/:cl:
=> Style momentos

code/datums/autolathe/guns.dm
10mm specialist is now propely name 9mm specialist when on a disk
=> subtracts one

code/modules/power/supermatter/supermatter.dm
<details>
<summary>
</summary>
<hr>
Gives supermatter actual price tag
<hr>
</details>
:cl:
balance: Rock of Yellow
/:cl:
=> Supermatter price

code/game/jobs/job/church.dm
<details>
<summary>
</summary>
<hr>
Title
<hr>
</details>
:cl:
balance: Custodian Wages
/:cl:
=> Custodian Wages

code/modules/mob/living/carbon/human/species/station/station.dm
<details>
<summary>
</summary>
<hr>
Gives each race it's own tempeture limits, makes it less punishing on opifex and cindarite, fixes typo in akula name
<hr>
</details>
:cl:
balance: racial tempetures
spellcheck: Akula name
/:cl:
=> Racial Tempetures

code/modules/mob/living/carbon/superior_animal/human/subtype/balkan/balkan.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/excelsior/excelsior.dm, code/modules/mob/living/carbon/superior_animal/superior_defines.dm
<details>
<summary>
</summary>
<hr>
Nerfs excel/merc mobs and ranged mobs reaction time
<hr>
</details>
:cl:
balance: Excel/Merc mob stats
fix: Insane reaction times
/:cl:
=> Reaction time

code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/projectile/automatic/broz.dm, code/modules/projectiles/guns/projectile/automatic/luty.dm, code/modules/projectiles/guns/projectile/automatic/specialist.dm, code/modules/projectiles/guns/projectile/automatic/umbani.dm
Fixes 9mm drums to be more visible now
Broz, Luty, and Five-Oh now accept 9mm drum magazines
=> 9mm drum fix

code/game/jobs/job/security.dm, code/game/objects/items/toys.dm, code/modules/client/preference_setup/loadout/lists/factionsecurity.dm, code/modules/clothing/head/jobs.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/under/jobs/security.dm
<details>
<summary>
</summary>
<hr>
Title.
<hr>
</details>
:cl:
fixes: Deputy Chief now has access to their own office.
fixes: Fixes improperly spelled names on items.
/:cl:
=> Fixes Deputy Chief's Names and Access

code/modules/economy/coalition_dinar.dm, code/modules/mob/living/carbon/superior_animal/human/subtype/balkan/balkan.dm
Fixes balkan mercenary mobs not dropping their currency
Fixes dinars being invisible
=> Dinar drop fix

code/game/objects/random/mob/misc.dm, maps/_DeepForest/map/frozen_crashsite.dmm, maps/_DeepForest/map/frozen_forest.dmm, maps/__Liberty/map/_Liberty_Colony.dmm
All Render spawns have been switched out for their Agape counterparts.
=> switches out renders for agapes

maps/__Liberty/map/_Liberty_Colony.dmm
Medical doors in medical no longer all synced badly to a single button
=> fixes some bad doors

code/modules/reagents/machinery/alchemy.dm
=> alembic sprite fix

code/datums/setup_option/backgrounds/ancestry/ancestry_kriosan.dm
I hate your format for this.
Also; touches up Kriosan ancestry, corrects an egregious mis-spelling and generally clarifies what each caste do, since Kriosan's had their racial abilities split.
<hr>
<hr>
</details>
:cl:
tweak: ingame Lore less goofy
/:cl:
=> Kriosan Ancestry Changes

code/modules/organs/external/subtypes/robotic_types.dm
Fixes limb armor.
Was not intentional.
=> waaaaaaaaaaaaaaaaaaaaaah

code/modules/dungeons/procedural/jp_dungeon_gen.dm
Adds in submap initilization to precursor dungeons so they load everything right.
=> precursor map initilization

code/modules/mob/living/carbon/superior_animal/ai.dm
Mobs now will also ask if the person is incapacitated well desiding if their health is to low, this should fix an abuse of low health people that are still attacking mobs that do not attack back
=> Better mob health check

code/modules/client/preference_setup/general/07_stats.dm
Fixes Willpower not displaying in the total points used blurb causing confusion
=> Fixes invisible willpower

code/datums/craft/recipes/lodge.dm, code/game/objects/items/animal_parts.dm, code/modules/mob/living/carbon/superior_animal/vox/vox.dm, code/modules/mob/living/simple_animal/hostile/bear.dm, code/modules/mob/living/simple_animal/hostile/big.dm, code/modules/mob/living/simple_animal/hostile/carp.dm, code/modules/mob/living/simple_animal/hostile/creature.dm, code/modules/mob/living/simple_animal/hostile/misc.dm, code/modules/trade/datums/trade_stations_presets/2-uncommon/KriosanConfederacy.dm
Pristine animal fangs can now stack..
=> makes pristine animal fangs stack

code/game/machinery/biosculptor.dm
After a PIRS and CAPSA joint effort, the Biosculptor is no longer limited to only recycling slabs of meat for useable biomaterial. Careful what you leave in the input, PIRS and CAPSA are not liable for any damages.
=> Biosculptor Renaissance

code/__DEFINES/mob_species_forms.dm, code/__DEFINES/perks.dm, code/datums/perks/backgrounds.dm, code/datums/setup_option/backgrounds/ancestry/ancestry_synth.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/organs/organ_description.dm, liberty-station.dme
Synths, RETURN!
Not an exact replacement for FBPs, but rather expands on the concept - and lets FBPs have their own unique goofy stuff, while also re-implementing true synths.
This is going to be a multi-part and very atomised slow-rollout and balancing of features. I am doing a lot of stuff to try and make them as fun and balanced as possible; and most of it is very goofy as a result in some circumstances.
:cl:
add: Re-adds synths and the framework for them.
/:cl:
=> SYNTHS, CONVERTS AND MECHANICALS.

code/game/machinery/crafting_station.dm
Fixes ammo crafting stations allowing free printing of endless ammo
=> worse returns on investment

code/game/objects/effects/decals/crayon.dm
=> fixes crayon magic

code/modules/dungeons/procedural/precursor.dm
Fixes precursor generator getting stuck in forever resetting loop.
=> precursor check var

code/game/objects/effects/decals/crayon.dm
Adds two more crayon scrolls for scribes to play with
=> two more scrolls

maps/submaps/precursor_rooms/end/end_rooms.dm, maps/submaps/precursor_rooms/large/large_rooms.dm, maps/submaps/precursor_rooms/normal/normal_rooms.dm, maps/submaps/precursor_rooms/starter/starter_rooms.dm
Heavily comments precursor tileset files to help mappers for slotting in their tilesets.
=> precursor tileset comments

code/modules/mob/language/rolion.dm
- Changes coalition language's key to P so that it doesn't conflict with cult language
<hr>
:cl:
fix: Changes coalition key to P so that it doesn't conflict with cult language (c)
/:cl:
=> Quick language fix

maps/__Liberty/map/_Liberty_Colony.dmm
Maybe fixes thermogenertors wiring
Fixes a convarer belt error
Replaces some wall lights in the bondfire with candle lights, as well as 2 plants with statues/other decrations
=> thermogener fix

code/datums/craft/recipes/machinery.dm, code/datums/craft/recipes/wall.dm
<details>
<summary>
Adds ability to craft wooden doors in "machinery" crafting tab, enabling anyone with 10 pieces of wood to make one.
</summary>
<hr>
<hr>
</details>
:cl:
add: crafting of wooden doors
/:cl:
=> Wooden Door crafting

code/game/machinery/cryopod.dm
adds the respawn bonus to cryopods. Tested and should be working now.
=> Potentially fixes cryopod respawn timers

maps/__Liberty/map/_Liberty_Colony.dmm
This PR makes the carpets look symmetrical. That's it. My OCD was bothering me.
:cl:
add: Added a double door to stronghold workshop.
/:cl:
=> Bigger Workshop Doors

code/modules/sanity/breakdowns.dm
Adds in 4 new good breakdowns
Adds in 5 new bad breakdowns
=> help i can hold all these new breakdowns

code/game/jobs/job/service.dm
removes the negative health for being a club worker.
Requested by someone that I can't remember the name of due to being tired.
=> club worker health fix

maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
adds precursor dungeon to PIRS mining outpost
=> PIRS precursor access

code/controllers/configuration.dm, code/controllers/master.dm, code/modules/tgs_integration/tgs_procs.dm, config/example/config.txt, liberty-station.dme
<details>
<summary>
</summary>
<hr>
Adds on init discord announcement with support for @ discord user or a discord role
<hr>
</details>
:cl:
Adds 4 config options related to announcing server restarts
/:cl:
=> More TGS Integration

code/datums/outfits/jobs/engineering.dm, code/game/objects/items/weapons/storage/belt.dm, code/modules/clothing/under/jobs/engineering.dm
here i added things that make sense for the union workers in shift start, an arc welder, 600 M cell, Engineering pouch, since they are engineers should start with that gear, is a bit of LV up in their starting gear but previously they were undergeared to make their work, spawning without welding protection and having to carry their materials in less convenient ways
other thing is that i MIGHT have done the coding of the new uniforms and the addition of them to the shift spawn  union workers
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
/:cl:
=> Union Addings

code/game/objects/effects/decals/crayon.dm, modular_liberty/cardgame_2/cardgame_2.dm, modular_liberty/cardgame_2/cardholder.dm, modular_liberty/cardgame_2/cardpacks_and_spawner.dm
Rebalances rat cards and deck (again)
Adds in a new system of cardcarp accessable only atm by crayon magic
Makes terrian cards slightly more likely to be in packets
=> card carp meets maker

config/example/config.txt
Small correction so the TGS will ping folks properly
=> forgotton _role

code/datums/lobbyscreen.dm
<details>
<summary>
</summary>
<hr>
<hr>
</details>
:cl:
Add: New Lobby Art
Remove: Meme Lobby Art (Live on in our hearts)
Change: Gives two unique music tracks on each picture
/:cl:
=> Lobby Enhancements

code/__HELPERS/game.dm, code/modules/core_implant/cruciform/machinery/obelisk.dm, code/modules/mob/living/carbon/superior_animal/superior_animal.dm, code/modules/mob/living/life.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/living_powers.dm, code/modules/mob/living/silicon/robot/life.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/sanity/sanity_mob.dm, modular_liberty/Borers/borer.dm
<details>
<summary>
did some testing and check_surrounding_area() was causing a shitton of lag.
Reason? It was checking every single mob on the Zlevel and asking if they were close enough.
New if() uses oview() which starts from the src and works outwards to a mob's world.view and respects their ability to see (see invisible, see in dark, etc.)
removed SSmobs.mob_living_by_zlevel altogether... Since there's no need to zlevel call every fucking mob (except for the junkbeam faction setting)
</summary>
<hr>
<hr>
</details>
:cl:
fixed: hopefully, lag from superior_mobs
/:cl:
=> BEGONE check_surrounding_area

code/modules/mob/living/carbon/superior_animal/superior_animal.dm
<details>
<summary>
creatures were emoting while dead.
Change an OR to the correct AND
</summary>
<hr>
<hr>
</details>
:cl:
tweak: A little bug with the bugs
/:cl:
=> No more death whispers

code/modules/mob/living/living.dm, code/modules/sanity/sanity_mob.dm
<details>
<summary>
Because sanity is really weird, yo.
</summary>
<hr>
<hr>
</details>
:cl:
Tweak: A few more things
/:cl:
=> Few more fixes to mob AI activation.

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/living.dm
<details>
<summary>
Fixed a NULL-value that caused mobs to be dumb
</summary>
<hr>
<hr>
</details>
:cl:
Fixed a thing
/:cl:
=> Fixed AI_INACTIVE on mobs versus humans

code/__DEFINES/perks.dm, code/controllers/subsystems/economy.dm, code/datums/perks/backgrounds.dm, code/datums/setup_option/backgrounds/path/path.dm, code/game/jobs/department.dm, code/game/jobs/job/job.dm, code/game/objects/effects/decals/crayon.dm, code/game/objects/structures/turf_spawner.dm, code/modules/core_implant/cruciform/machinery/eotp.dm, code/modules/modular_computers/file_system/reports/crew_record.dm
Crafting underplate now shouldnt break tile lighting
Changes naming of the EOTP to be more in line with wanted lore
Converts nepotism  - > Valued Employee, for greater character flexablie 
Maybe fixes a issue with life to cards
=> misc bug fixes and slight changes

code/modules/mob/living/carbon/superior_animal/liberty/FreeportMobs.dm
<details>
<summary>
Fixes some mob names and descriptions; cleared by Nayu and Medi.
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Fixes errors in mob names.
/:cl:
=> Fixes for Event

code/game/objects/items/oddities_faction.dm
=> exploit fix

code/game/world.dm
<details>
<summary>
Title
</summary>
<hr>
<hr>
</details>
:cl:
fixes: Adds new server description to display on hub.
/:cl:
=> Updates Server Description

code/datums/craft/step.dm, code/game/objects/effects/decals/crayon.dm, modular_liberty/cardgame_2/cardgame_2.dm
Fixes an error with gereration with card carp cards
Fixes an error with allowing you to null cells/items when crafting items using storage items or other tools/devices
=> fixes some nulling

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
adds an erp uniform for the fixers, allowed by nayu so the fixers provide "special" service the soon as possible?
</details>
adds a leather uniform
:cl:
add: adds a leather uniform for skylight
/:cl:
=> erp uniform

code/modules/projectiles/projectile/bullettypes.dm
makes the buckshot become useful at long and close range, maybe losing his PB effect but becoming ideal to kill roaches, injure enemies without armor and making it a more useful ammo
:cl:
tweak: makes the buckshot be long range ammunition with 7 pellets equal to a weak 9mm round, mostly a test 
/:cl:
=> long range buckshot

maps/__Liberty/map/_Liberty_Colony.dmm
adds an lower room to skylight, mainly a spectacle area that can be modified by the workers to do shows or convert in something they want, the area is powered by the cargo apc, doesn't have any camera and starts as an arena with some basic knuckledusters, boxing gloves and scrap helmets/ armors for the fighters
mostly an area to make events, fights or recycle into an work station for the shift, be creative
:cl:
Add: adds a new room to skylight using an unused space
/:cl:
=> Secret club....(50 scrips the ticket!)

maps/__Liberty/map/_Liberty_Colony.dmm
adds new 5 new dorm rooms to the lower floor, adds courtains to the engineering areas in the colony to avoid be instantly targeted by critters when an engineer appears there to check something
🆑 Add: adds 5 dorm rooms and some courtains in the engineering ladders 🆑
=> Neew dorms

code/datums/setup_option/backgrounds/ancestry/ancestry_human.dm, code/datums/setup_option/backgrounds/path/path.dm, code/datums/setup_option/backgrounds/thoughts/thoughts.dm
for some reason someone buffed the early start of the characters going with +5 and +10 stat points in some areas, this reverts the clearly convenient start for some characters since is not fair.
:cl:
balance: nerfs some stat points in character creation for humans
/:cl:
¡
=> balances in character creation

code/modules/client/ui_style.dm, code/modules/mob/living/carbon/human/human_hud.dm, code/modules/mob/living/living_hud.dm
What it says on the tin.
That fix allows to change HUD style on the fly.
https://github.com/Liberty-Landing/Liberty-Station-13/assets/65828539/581bcccf-c76d-461b-8b94-049b5fb0c617
:cl:
fix: Fixed HUD overlap on style change
/:cl:
=> Fix HUD overlap on style change

code/modules/mob/living/carbon/human/species/station/station.dm
Temp disables 
Naramad
Akula
Sudak
Opifex
Mar'qua
Mycus
Cht'mant
Cindarite
Untill their lore is handled
=> temp disable

maps/__Liberty/map/_Liberty_Colony.dmm
adds 5 entrances to the future sewer dungeons, updates some loot in a spider den while also reduces their numbers (a nest was under a stone so it was like a lot of spiders)
:cl:
<!--add: Added new things
add: Added more things
del: Removed old things
balance: rebalanced something
fix: fixed a few things
/:cl:
=> maint rework

maps/_DeepForest/map/frozen_crashsite.dmm
reworks the area adding a raided village (low tier dungeon for fontaine and outsiders), re mapping the mercenary dungeon (ex colony area?) adding a landing pad for event stuff, adds more iron eagle references, adds a cloning area for the mercenary dungeon (just a frame where the cloning machine was, leading to the conclusion that the machine was stolen by the mercs and im gonna use that for introduction in new mutant enemies made by the mercs and other antag faction)
:cl:
add: Added more dungeons
del: Removed old prison
/:cl:
=> frozen crashsite rework

maps/__Liberty/map/_Liberty_Colony.dmm
makes the wall less babyproof, decorates the outside of the colony as a raided land like is supposed to be, deletes some weird loot in the outside?, adds a local helldiver cave in the colony fence since he is the original owner of the cave
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
/:cl:
=> wall update

code/game/objects/items/weapons/material/knives.dm, code/game/objects/items/weapons/tools/knifes_daggers.dm, code/modules/mob/living/damage_procs.dm
Backstabbing in alt mode is now properly LTL
Fixes backstabbing with closed knifes no longer works
:cl:
Backstabbing in alt mode is now properly LTL
Fixes backstabbing with closed knifes no longer works
/:cl:
=> backstab damage fixes

maps/_DeepForest/map/Forest-pre-village.dmm, maps/_DeepForest/map/Forest-space_scrap.dmm, maps/_DeepForest/map/frozen_crashsite.dmm, maps/__Liberty/map/_Liberty_Colony.dmm
they were too sneaky....
fixes some space tiles on the crashlanding map
:cl:
fix: fixes some things
;cl:
=> fixes space tiles
