code/game/machinery/kitchen/smartfridge.dm
Stops medi borgs from putting their syringes in the fridge.
(Didn't spend to much time testing this one. I couldn't get the medical syringe to go into the fridge I spawned in.)
=> borg syringe fix

code/game/machinery/atmoalter/scrubber.dm, code/game/turfs/flooring/flooring_premade.dm, code/game/turfs/simulated/wall_types.dm, code/game/turfs/unsimulated/floor.dm, code/game/turfs/unsimulated/walls.dm
<details>
<summary>
this is just a bunch of tools for mappers to start making snowy places cold (-20 celcius), click for more details
</summary>
<hr>
- tested on the soj map, the outside made the server take a small hit right as the server started, since I only drew a line of unsimulated snow, making it fight with the normal turfs for a while, once temp and pressure stabilized the lag died, but overall satisfactory method of making outside always have air and always be cold
- the skadi yggdrasil works exactly like the other one (i've made it a child of it) except it operates at -20 celcius and keeps a pressure of 99.4kpa of breathable air, differently from the unsimulated turf this one simply changes all the air in the area to this, little processing required, good for large areas
- my …
=> Cool map tools

code/datums/perks/racial.dm, code/datums/setup_option/backgrounds/origin_career.dm, code/datums/setup_option/backgrounds/origin_kriosan.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/reagents/reagents/race.dm
<details>
<summary>
</summary>
<hr>
Finally splits the perfect shot from all kriosans to just vorhut and gives jaeger bolting perk, second skin now only halves armor slowdown instead of entirely removing it.
Kriosan and Naramad boosts now have withdrawal effects just like akula and had what they do changed, akula perk now actually gives painkiller again after long 2 years and other smaller changes to keep the aliens bit in line with themselves rather than humans
<hr>
</details>
:cl:
balance: Alien perks
/:cl:
=> Perk perkinson

code/game/objects/effects/decals/Cleanable/humans.dm, code/game/turfs/flooring/flooring.dm, code/modules/mob/living/carbon/superior_animal/psi_monsters/types/Ploge.dm, code/modules/mob/living/carbon/superior_animal/xenomorph/types/XenoRobust.dm, code/modules/mob/living/simple_animal/hostile/bear.dm, code/modules/sanity/sanity_mob.dm
<details>
<summary>
</summary>
<hr>
Complicates the underplating code for no reason with making it so while lying down or getting dragged while knocked out it no longer damages you, Klutz and negative vigilance also have way higher debuff now and Klutz no longer stacks with Sure Step for purposes of ignoring underplating as you are still a klutz. It also now accounts for Vigilance again instead of Cognition but this will make sense right after this.
Examining footsteps is based on cognition now instead of vigilance, plain reason not only vigilance does too much but being smart would help you way more in deducing crime and details than just being plain perceptive.
Santy checks now fully rely on Cognition, not Vigilance, as the one before, vigilance is measurment of …
=> Harry, you forgot your stats!

code/game/machinery/vending.dm
Gives vendors a var that when set to anything besides null makes them take research points to purchase things.
These points have to be on a data disk (the portable hard_drive one code wise)
Currently no vendors use this yet. Just the framework for later creations.
=> vendor research data var

code/modules/core_implant/cruciform/rituals/construction.dm
Ports over K5's fix https://github.com/sojourn-13/sojourn-station/commit/b47b2fc01de4cf2a51a46c3afe904bf89adb1eb3
That corrects stacking 500000 decons and getting freeee endlesss materals!
=> Fixes decon prayer stacking

code/__DEFINES/perks.dm, code/datums/perks/racial.dm, code/game/objects/items/weapons/storage/backpack.dm, code/modules/mob/living/carbon/brain/brain_item.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_helpers.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species/forms/station.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/slime/life.dm, code/modules/organs/external/subtypes/slime.dm, code/modules/organs/organ_description.dm, code/modules/reagents/reagents.dm, code/modules/reagents/reagents/core.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/toxins.dm
<details>
<summary>
- 	not really in, reagents snowflake code needs to be discussed, simply inverting the tox_mod seems like a surefire way to guarantee it will work
- currently there is a runtime in reagents because of the snowflake code
- this pr requires TESTERS, specially people good at mobcode
- needs input on the perks, to keep them aligned with the others (lamas moment)
</summary>
<hr>
<hr>
</details>
:cl:
add: slime people
/:cl:
=> The slimes are in* (*not entirely, but playable)

code/game/objects/structures/crates_lockers/closets/secure/fontaine.dm
Fontaine lockers spawning revolver sidearms gave 9mm speedloaders, but the revolver it spawns uses 10mm, sets the speedloaders to 10mm instead.
=> Corrects bullets in Fontaine lockers

code/datums/outfits/jobs/prospector.dm, code/modules/clothing/head/jobs.dm, code/modules/clothing/suits/fontaine.dm
- Adds Fontaine's helmets in-game by adding them to their jobs' roundstart clothes
- Corrects Shepherd helmet spritepath
- Adds Lower Body coverage to the Trapper greatcoat since it only covered upper body and that's a bit silly when even vests reach the Lower Body, arguably it should cover the legs too but SHRUG.
Ready for review, someone else is handling the erroneous female sprites for the clothes.
=> Fontaine clothes adjustments

code/game/objects/items/weapons/storage/hardcases.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Fixes the shepherd primary selection giving the wrong ammo.
Fixes the debug revolver spawning in cargo tech lockers, replaced by the Frontier revolver which is still 10mm Magnum as the ammo indicated.
=> fixes erroneous paths

code/game/objects/structures/flora/tree/flora_snowtree.dm, maps/_DeepForest/map/frozen_forest.dmm, maps/__Liberty/map/_Liberty_Colony.dmm
Adds medicinal flora spawners around the maps. Amount will be adjusted as feedback shows during play.
Adjusts snow trees' pixel_x and pixel_y offsets to match their sprites better and have a more sensible collision tile.
Removes a window in Fontaine that blocked access to a corner, fixes #119.
Moves Trapper and Shipbreaker spawn locations to their correct sides.
=> medicinal flora and a few things

code/game/objects/items/weapons/grenades/flashbang.dm, code/modules/mob/living/silicon/robot/gripper.dm
These looked easy so. Ports Eris PRs #8115, #8103 and #8125
Flashbangs now also apply a Robustness penalty.
Flashbangs now apply recoil based on your ear protection level.
Service and Paperwork grippers can grip more things, most notably Cash and EFTPOS devices for the former.
=> small ports

code/__DEFINES/perks.dm, code/datums/setup_option/backgrounds/habit/habit.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/food-Drinks.dm
<details>
<summary>
</summary>
<hr>
Removes Herbi/Carnivore perks as they are extremely buggy in their implementation
Gave Honey Glucose and Sugar overdose effects and limits while reducing their effectivness to bypass actually eating food
<hr>
</details>
:cl:
del: Herbi/Carnivore
balance: Honey Sugar Glucose bypassing need to eat entirely
/:cl:
=> Sugar Honey Glucose

code/game/jobs/job/service.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Alters club manager locker to not have excess junk and cargo items
Gives club manager actual command flag and a time lock like other heads.
Changes cargo tech lockers into fixer lockers.
Removes a shit ton of stuff from cargo tech lockers. Holy hells why did they have bluespace bags?
Gives fixer lockers a hard spegetti spawn cause mob family.
Gives fixer lockers a random mob like melee weapon.
Fixes cargo headset spawns in lockers to be service headsets instead.
Gives club manager access to department funds.
=> service job fix

code/datums/autolathe/biomatter.dm, code/game/gamemodes/scores.dm, code/game/machinery/vendor/weapon_vendors.dm, code/game/objects/items/oddities_faction.dm, code/game/objects/items/toys.dm, code/game/objects/items/weapons/autolathe_disk/bonfire_disks.dm, code/game/objects/items/weapons/nt_melee.dm, code/game/objects/items/weapons/storage.dm, code/game/objects/items/weapons/storage/firstaid.dm, code/game/objects/structures/noticeboard.dm, code/modules/core_implant/cruciform/bible.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/organs/external/subtypes/robotic_types.dm
Adjusts a lot of church equipment strings (mostly weapons) to the updated Custodian strings based on their document, sprites still pending.
Adjusts Custodian-related things from using biomatter and plasteel to their bio-silk and carbon fiber.
Removes custodian base weapon item in-game and clearly spells out it is not to be used in case I missed another instance.
=> custodian strings and materials

code/ATMOSPHERICS/components/unary/outlet_injector.dm, code/game/machinery/spaceheater.dm
too hot 🥵
also injectors tweak, all piping works at 200 liters, or 400 in case of the old filters, starting at 50 is asking to be clogged
:cl:
balance: makes space heaters a little less hot
tweak: injectors now start at 200 liters, from 50
/:cl:
=> atmos tweaks

code/__DEFINES/perks.dm, code/datums/perks/job.dm, code/game/jobs/job/service.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, maps/__Liberty/map/_Liberty_Colony.dmm
Reallows club workers to see common reagents
Adds 2 more dinnerware venders
Adds more trash cans around the lower areas
moves around some no smoking signs to no longer overlap into public areas 
fixes stacked airlock issues
Fixed some missing named pets
Fixed missing hog for garden
Renames hog to be more lore-friendly
=> map tweaks and common sense

code/modules/reagents/machinery/grinder.dm
allows silicons to access the ui of grinders on sight, but not insert mats into it
:cl:
fix: robots are not forced to use the gripper to access the grinder anymore
/:cl:
=> roboto accessoh!

maps/__Liberty/map/_Liberty_Colony.dmm
turns out the miners had mapped access to cargo, nevermore
:cl:
fix: fixes access to cargo from miners
/:cl:
=> miner no cargoing

maps/__Liberty/map/_Liberty_Colony.dmm
robotics was missing one, not anymore
armory button now fixed too
:cl:
fix: missing firedoor in robotics
fix: missing button on the armory shop
/:cl:
=> few map fixes

code/__byond_version_compat.dm, code/_compile_options.dm, liberty-station.dme
this file is mostly defines that allow us to slowly upgrade to 515 while operating as 514
it only really matters to coders right now, so 🤷 
the new file was taken from TG, adapted to our codebase by me
:cl:
code: more stuff to allow us to code in 515 while operating in 514
/:cl:
=> the bridge to 515

code/game/objects/items/stacks/tiles/tile_types.dm, code/game/turfs/flooring/flooring.dm, code/game/turfs/flooring/flooring_premade.dm
With the addition of the other damaged tiles their was no way to use them in normal rooms, this adds a new type that dont randomizes for mappers to use so you dont have to have 300000 broken tiles
=> makes the new types of floors have a nonbroken type

code/modules/projectiles/guns/projectile/automatic/duty.dm, code/modules/projectiles/guns/projectile/automatic/lmg.dm, code/modules/projectiles/guns/projectile/automatic/nationale.dm, code/modules/projectiles/guns/projectile/automatic/tactical.dm
Here we go again.
Duty rifle grip mismatch fixed, now takes wooden grips and can be crafted.
Dragon marksman rifle variant of the Nationale rifle now takes 7.62 barrels and can be crafted.
Tactical SMG now takes 10mm barrels and can be crafted.
Hog LMG is now properly 6.5mm.
<hr>
</details>
:cl:
fix: Duty frame and gun mismatched grips fixed, frame now takes wood
fix: Nationale dragon barrel switched from srifle to lrifle
fix: Tactical SMG switched barrels from pistol to magnum
fix: Hog LMG removed instances of lrifle and CAL_RIFLE, now srifle and CAL_SRIFLE
/:cl:
=> Gun fixes 2.0

maps/__Liberty/data/_Liberty_factions.dm
fixes a small mistake on the fax machine
:cl:
fix: Skylight Boss name on the fax machine
/:cl:
=> that is how mafia works

code/game/objects/landmarks/join.dm, maps/_DeepForest/map/frozen_crashsite.dmm
Changing disallow_job out for restrict_job since it's more reliable. Think the disallow_job check has bad logic since it refused even Outsiders and did not refuse colony jobs from spawning.
Of note is that no spawn points exist for Outsider Bed, everything "outsider" is in old-cyro-spawn, but I don't even know how I'd fix that.
Tested on a local copy up-to-date to the point #298 was merged, late-joined as Outsider on colony spawn points, was refused and it randomly checked spawn points until it reached old-cyro-spawn and let me through.
Late-joined as Colonist on Outsider spawn points, it refused and checked until it found one that would allow me. (lower elevator, cryo, etc)
Didn't test Robot that much but there should be no problem since restrict_job seems to work well.
=> Fixes faulty spawn behavior

code/game/objects/items/weapons/storage/hardcases.dm, code/game/objects/random/guns.dm, code/modules/clothing/chameleon.dm
Add: Watch now starts with a medium cell in their hardcase for use with their counselor stun pistol.
Fix: Chameleon guns have had their functionality restored.
Removed: Reductor and a debug railpistol have been removed from dungeon loot pools as they require balancing.
=> General fixes

code/game/gamemodes/events/migration_ameridian.dm, code/game/gamemodes/events/migration_vox.dm
Fixes the Vox bird migration and Ameridian growth events, these only affect the immediate colony surroundings and do not spawn in wilderness z-levels anymore. Subject to change if the need arises.
Tested on a local server, forcing Major-tier events for both successfully spawned monsters and launched an announcement afterwards.
=> Restores Vox and Ameridian spawning events

code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
Adds in claw energy drinks to the vermouth trade station as a hidden section.
Fixes booze barrels not having booze in them.
=> vermouth station

maps/_DeepForest/map/frozen_crashsite.dmm, maps/__Liberty/area/_Liberty_areas.dm
Adjusts the areas making up the unknown mercenary bunker to not require power, allowing the lights, the vendor (and most importantly) the advanced turrets to function.
Adds missing invisible lights surrounding the unknown mercenary bunker to simulate daylight streaming in, just like all other locations.
=> Mercenary Bunker Area and Outdoor Lights

code/game/jobs/job/church.dm, code/game/objects/items/weapons/nt_melee.dm, code/game/objects/items/weapons/tools/misc.dm, code/game/objects/structures/custodian_decorations.dm, code/modules/core_implant/cruciform/machinery/eotp.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/upgrades.dm, maps/__Liberty/map/_Liberty_Colony.dmm, nano/templates/bioreactor.tmpl
Fixes some erroneous strings still talking about biomatter and/or Cruciforms.
Sets the statue layers to their correct setting, acting more like trees.
Removes the duplicate perklist for Forgemasters, causing an overwrite.
Set the Forging Touch to be placed into any hand, prioritizing the active hand, rather than canceling if the active hand is occupied.
=> Custodian Bug-Fixing 2: The Crisis at San Diego

maps/_DeepForest/deepforest.dm
!! WARNING !!
This turns generate_asteroid to TRUE on the frozen crash site map data so the unsimulated mask objects placed there are able to generate ore, due to this, initialization takes a bit longer. It's up to the staff to decide if they want this extra initialization time so ores can generate in the frozen crash site, or if the mask objects should be removed, but currently, they show up as unsimulated mask tiles on the live server for anyone to stumble on. So that's bad.
=> Enables mask generation on frozen crash site

code/game/objects/items/_inventory.dm, code/game/turfs/flooring/flooring.dm, code/modules/mob/inventory.dm
<details>
<summary>
</summary>
<hr>
Ports a variety of Eris QOL PRs. Guns shouldn't fire when you drop or holster them as if they were still in your hand, wielding an object in your hand while holding another makes you drop the non-wielded item instantly; allowing quick wielding. And no-slips stop from you form.. well - slipping on undertile.
<hr>
</details>
:cl:
fixes: No more holstering/dropping a gun but shooting an invisible gun in your hand.
adds: Wielding now makes you drop any item in the opposite hand.
tweak: No-slips now.. act like no-slips. You can't slip on undertile wearing them anymore. (Did you know 50 vig stops you from tripping too???? Quirky.)
/:cl:
=> Take 2: QOL and Eris Wielding port

code/modules/mining/drilling/drill.dm, code/modules/mining/drilling/termite_burrow.dm, code/modules/mining/drilling/termite_wave.dm, maps/__DeepTunnels/map/_Liberty_Deep_Tunnels.dmm
Subsurface ore scanners have been moved to a more visible location.
Drill heads now have a verb to configure their internal "Seismic Stimulator" in order to intentionally provoke or bait larger termite swarms, this does not let you lower their aggression, only increase it if desired.
Drill heads now fully excavate an entire tile before selecting another random tile in their range.
Drill head's base mining speed has doubled.
Termite burrows are not dense anymore, but have lost the ability to be destroyed by force, they only dissapear when the drill is stopped and the termite waves cease.
Termite waves' downtime between waves and new burrows spawned has been decreased.
=> Drill mining adjustments

code/modules/economy/coalition_dinar.dm, code/modules/projectiles/guns/projectile/revolver/ranger.dm
Fix: Ranger revolver frame renamed from Minotaur to Ranger.
Fix: Large stacks of dinars no longer vanish.
=> Gun and sprite fix

code/game/gamemodes/events/migration_ameridian.dm, code/game/gamemodes/events/migration_vox.dm, code/game/gamemodes/events/rogue_drones.dm
Fixes the rogue drone event, as I missed it when fixing the Ameridian and Vox spawning events.
Both the Ameridian and Vox spawning events now leave behind 15% of the spawned mobs when ending instead of deleting them all.
=> Fixes rogue drones, adjusts end event for vox and ameridian events

modular_liberty/spaceleak.dm
Makes bluespace leaks not give a guaranteed positive breakdown when stepped on.
=> Bluespace leak breakdowns

code/modules/mob/inventory.dm
defibs now longer null themselfs and get stuffed inside people when used
=> fixes defibs

code/modules/trade/datums/trade_stations_presets/1-common/boozefood.dm
adds the "render" energy drink that for some reason was not grouped with the rest of the energy drinks code wise to vermouth station.
=> vermouth missing energy drink fix

code/datums/craft/recipes/guild.dm, code/datums/craft/recipes/pirs.dm, code/game/objects/items/weapons/stock_parts.dm, code/modules/clothing/glasses/powered.dm, code/modules/projectiles/guns/mods/mods.dm, liberty-station.dme
Guild VS PRS
:cl:
add: Most union recipes to PIRS
del: Most union recipes from union
add: New union recipes
tweak: NVGMesons exist properly now
tweak: Lots of union recipes are now cheaper than the PIRS alternatives.
QOL: Union things are generally cheaper + faster to make (and more worthwhile)
/:cl:
=> Moving crafting recipes from Union to PIRS, giving Union cheaper alternatives of some recipes, and generally QOLing some of their stuff

code/modules/dungeons/procedural/precursor.dm, maps/_dungeons/precursor/precursor.dmm, maps/submaps/precursor_rooms/end/pruin_end1.dmm
Changes dungeon reset item to be a unique item so you don't find the loot somewhere else by chance.
Adds a few things for the testing room so I don't die to lack of gas or the temp change from some anomaly.
Fixes up the PSD to have a better sprite by Gidgit and be solid.
Fixes PSD not actually consuming the dungeon reset item. (infinite reset fix)
=> precursor bug fix pass 01

code/datums/craft/recipes/guild.dm, code/datums/craft/recipes/pirs.dm, code/datums/craft/recipes/robot.dm, code/datums/craft/recipes/tools.dm, code/game/jobs/job/medical.dm, code/game/objects/items/weapons/storage/boxes.dm, code/modules/research/nodes/engineering.dm
Tweaked PR #388 to be a lot more fair and lore friendly to both PIRS and TT-Union
:cl:
balance: Moved exosuit and borg augments originally inside the PIRS general craft to the Robotics tab.
balance: Added back T4 craft for Union, but they can't make the bulk recipe to create redundancy  
tweak: Made the following items unrestricted crafts (let me know if they're duplicated somewhere): payload arrow, rubber mesh
tweak: Returned the Booster, Injector, Plasma Block, and Rubber Mesh to PIRS Protolathe, given they're going to be the faction you go to for Tool/Gun/Armor mods with the armor mods system expanded in the future
del: Tool related things from PIRS craft, as tools are Union's thing
del: Tesla relay recipe, as it skips intended research progression and it's cheaper if you research it …
=> #388 Augment

code/modules/dungeons/procedural/precursor.dm, code/modules/maps/tg/map_template.dm, maps/_dungeons/precursor/precursor.dmm
Fixes up bad bugs in the precursor dungeon generator
Gives precursor generator slightly better quality of life touches
Makes it so the reset dosn't spam admins with almost crushing potential player mobs.
Adds a few things to the precursor test fob.
=> precursor bug fix pass 02

code/modules/dungeons/procedural/precursor.dm, maps/_dungeons/precursor/precursor.dmm, maps/submaps/precursor_rooms/normal/hydro.dmm
Preps precursor dungeon code for the machine to be placed in PIRS
Creates new marker for the precursor map. Helps code of the precursor device find the dungeon z level.
Fixes a space tile in the dungeon generation that would empty the air out of most of the dungeon.
=> precursor PIRS prep

maps/__Liberty/data/_Liberty_factions.dm
<details>
<summary>
The following PR just renames the old Augustine Browne fax tooltip to Spark Liekki Korhonen. Nothing major.
</summary>
<hr>
<hr>
</details>
:cl:
tweak: Fixes the fax machine to have the right name.
/:cl:
=> Custodian Fax Rename

code/modules/sanity/sanity_mob.dm
Changelog:
Removes REAGENT TAG SYNTHETIC from sanity checks due to the fact our synthetics may need to level up. I am designing a better system for this - and it is no longer required due to changes. Also allows FBC to finally use sanity (as intended!)
=> I dont think I will.

code/modules/organs/blood.dm
Title!
:cl:
balance: Makes heart damage WAY easier to diagnose for the player afflicted by it, and makes it a tad less lethal too. This ended up being a major killer of outsiders, and general players due to the fact the only warning used custom_pain.
/:cl:
=> Oofie Owchies, My HEART is BROKEN

code/game/objects/structures/crates_lockers/closets/job_closets.dm
Bad pathing on populate_contents proc made it empty on initialization, this should fix the proc by using proper pathing
:cl:
fix: Oathpledge locker now properly has its intended contents instead of being empty
/:cl:
=> Oathpledge locker quickfix

code/game/jobs/job/service.dm, code/modules/clothing/accessories/accessory.dm
<details>
<summary>
This PR was made to give diversity to the Club Manager role by giving them alternate title names. Club Manager was a bit deterministic so this gives people mobility to do stuff.
</summary>
<hr>
<hr>
</details>
:cl:
adds: job manager alt names.
tweak: renames the cloak names to be job title neutral.
/:cl:
=> Club Manager Alt Titles & Cloak Tweaks

code/datums/topic/admin.dm
Did you know 1/4 Bay servers have incorrect flags for 90% of their admin commands? No? Well that's bad!
:cl:
admin: Fixes a few security vulnerabilities that allowed server-crashing capabilities, gave the average dev/maintainer/moderator access to jump to players and other basic tools.
/:cl:
=> WOE, WOE INDEED.

code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
sets the xenoarch replicator icon to be anomaly 120 instead of a missing icon file.
=> xenoarch replicator icon fix

code/datums/autolathe/biomatter.dm, code/game/objects/items/weapons/nt_melee.dm, code/modules/biomatter_manipulation/bioreactor/bioreactor.dm, code/modules/biomatter_manipulation/bioreactor/biotank.dm, code/modules/biomatter_manipulation/bioreactor/console.dm, code/modules/biomatter_manipulation/bioreactor/loader.dm, code/modules/biomatter_manipulation/bioreactor/platform.dm, code/modules/biomatter_manipulation/bioreactor/port.dm, code/modules/biomatter_manipulation/toxic_biomass.dm, code/modules/core_implant/cruciform/cruciform.dm, code/modules/core_implant/cruciform/rituals/base.dm, code/modules/core_implant/cruciform/rituals/group.dm, code/modules/core_implant/cruciform/rituals/machinery.dm, code/modules/core_implant/cruciform/rituals/path.dm, code/modules/core_implant/cruciform/upgrades.dm, code/modules/genetics/creatures/wasonce.dm, code/modules/mob/living/carbon/superior_animal/roach/life.dm, code/modules/organs/internal/carrion.dm, code/modules/reagents/reagents/toxins.dm
I had these sitting on my machine for a while, might as well push them.
Corrects "Cruciform" and "Bioreactor" names in a few places.
Changes scorch_attack() to not have hardcoded damage, now it can be changed when called
Adds visible messages and texts to Carrier Pigeon to not make it look like telepathy as much.
Makes power-using weapons actually consume power, buff durations and costs changed.
Makes custodian weapons more expensive and makes a few have less harsh alt_mode penalties.
=> custodian tweaks again

code/_onclick/hud/screen_objects/robot_screen_objects.dm, code/modules/projectiles/projectile/ameridian.dm
Attempts to fix a small hud issue with borg huds
Changes ameridian shard to be less lethal, have less AP and now check melee armor rather then bullet to make that miner voidsuit bit more viable
=> small rebalance to rock and hud fix for bot

code/datums/craft/recipes/furniture.dm
Reduces the crafting time of the Soil bed for crops by 30%
Huge timesink if you want to do it in mass, no tools being used that could speed up the process.
Heavily a personal tweak, for convenience.
It compiles, and there's nothing to really screenshot to show it working in action. so.
=> Soil craft time reduction

code/datums/craft/recipes/tools.dm, code/game/objects/items/devices/organ_module/active/multitool/makeshift_multy.dm, maps/__Liberty/map/_Liberty_Colony.dmm
You can no longer remove the implant aspect of makeshift multy tool
Replaces makeshift multy tool tools with the proper implant
Gives the makeshift multy tool icon to the makeshift multy implant
=> tweaks toolimplant multy
